### PR TITLE
fastFM-0.2.6 compilation issues on ubuntu 16.04

### PR DESCRIPTION
**Pull request by grizzo2**
All these notes are related to the binary archive downloaded by the "pip install fastFM" command. (the sources compilation runs ok):

1) I had to add the file fastFM-0.2.6/fastFM/cffm.pxd copying it from the source archive to fix "cs_di is not a type identifier" installation error,because the binary archive is missing this file.

2)  To run the C tests from inside the binary folder,since by default these tests are not included in the binary archive, I manually copied the src/tests inside fastFM-core extracting it from the source archive to see if they would run out of the box inside the binary folder;

Since the cxsparse static library is already provided precompiled in  the binary archive in the path fastFM-core/externals/CXSparse/Lib/libcxsparse.a, I had to comment the command to compile the cxsparse library in fastFM-core/src/tests/Makefile
'#	( cd ../../externals/CXSparse ; $(MAKE) library )'
(otherwise this command gave an error "No rule to make target 'library'" since there was no Makefile nor sources for this library included in the binary archive)

I was just thinking whether it could be useful to include the tests executables directly in the binary archive, so they don't need to be compiled to check the binary installation functionality.

Here I uploaded an archive of the binaries with the fix for point 1 and where I added a new "run_C_tests" folder containing the C tests executables with a batch executable run_C_tests.bat which can be run directly: 
[fastFM-0.2.6.tar.gz](https://github.com/ibayer/fastFM/files/708821/fastFM-0.2.6.tar.gz)

### CODE REVIEW

**Comment by ibayer** [comment]
Thanks for the PR. Can you change it so that only you changes show in the dif.
Right now it's really hard for me to review your changes.

**Comment by ibayer** [comment]
Can you open this PR against the master branch instead of 'fix_api_doc'?

**Comment by grizzo2** [comment]
Hi Immanuel, I am trying to understand how to use 
the github revision control system: 
When I try to create a new PR I have to choose a compare branch 
different than the base, because evidently the compare 
 is the new branch where the changes will be placed.

The choices it gives me are only:

fix_api.doc
gh_pages
release_0.2.5
master

I can't choose the master because it's already in the base selection,
so which one would you want me to choose for the compare ?

(I also could not find a branch in the github for the binaries  to fork from to put the changes
it only shows the branch for the source code ibayer/fastFM)

Glauco

**Comment by ibayer** [comment]
Do this instruction make sense?
http://scikit-learn.org/stable/developers/contributing.html#contributing-code

**Comment by grizzo2** [comment]
Hi Immanuel, 
I cloned again the ibayer/fastFM repo with git and compiled and installed and it works perfectly without any changes.
(basically If I fork the ibayer/fastFM repo there is nothing to fix there because this archive is already working)

The problem is only with the binaries archive downloaded using the "pip install fastFM command":
I am not sure how this binaries archive is generated, but that is the one that needs the fix: this is the file located at  https://pypi.python.org/pypi/fastFM/0.2.6

 fastFM-0.2.6.tar.gz (md5) 	Source 		2016-10-13 	366KB

I would upload this same archive to which I added the fix,that now is on my disk (the one I also uploaded on the PR), but I am not the owner of this pypi database account, so I don't think I can overwrite this file.

Let me know how you would like me to proceed.

Thank you,
Glauco

**Comment by ibayer** [comment]
Ok, I just had a look at your archive and understand now what you changed. I'll upload the fixed binary so I guess we can close this pull request.

**Pull request closed without merging**
