### PR TITLE
Fix private repo access

### PR DESCRIPTION
**Pull request by AlexJoz**
So, the access to private core2 repo and library build are working fine on linux, but travis osx build fails due

>ld: targeted OS version does not support use of thread local variables in __ZN6loguru22get_thread_ec_head_refEv for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Maybe you know this issue? Or i can analyze on weekend..

### CODE REVIEW

**Comment by ibayer** [comment]
Very nice to see that you got the linux test working.

I don't think I have seen the OSX link error before. The other travis config might
contain some relevant pieces.
https://github.com/ibayer/fastFM-core2/blob/master/.travis.yml

The error message might indicate that linking with `pthreads` goes wrong but thats just
a wild guess.
https://github.com/ibayer/fastFM-core2/blob/master/fastFM/CMakeLists.txt#L35

**Comment by ibayer** [comment]
https://github.com/CoolProp/CoolProp/issues/502
https://github.com/SFTtech/openage/issues/308

**Comment by AlexJoz** [comment]
tired of this already.
I have no osx now to test locally (

**Comment by ibayer** [comment]
@AlexJoz Thanks for fixing the Linux build!

**Pull request merged**
