### PR TITLE
Add manylinux1 build on travis

### PR DESCRIPTION
**Pull request by chezou**
This PR adds building manlinux1 wheels on travis-ci.

This work mostly depends on @chittti 's work
https://gist.github.com/chittti/c95de0bd1bab8340c34b59d1be21bb26
https://gist.github.com/chittti/bfa4f4fdc2d8ab9e8be01ce2dd087cce

close https://github.com/ibayer/fastFM/issues/122

### CODE REVIEW

**Comment by ibayer** [comment]
Thanks, having manylinux integrated with travis would be great. :-)

>   /opt/rh/devtoolset-2/root/usr/libexec/gcc/i386-CentOS-linux/4.8.2/ld: i386:x86-64 architecture of input file `fastFM-core/bin//libfastfm.a(cs_entry_di.o)' is incompatible with i386 output

I think @chittti had issues with i386 too and we decided to only providing 64bit binaries for now.

**Comment by chezou** [comment]
All right. I've just removed 32bit build with https://github.com/ibayer/fastFM/pull/125/commits/f3a6c5ab842c357165bba5b0d66426172c551e52 .

**Comment by chezou** [comment]
@ibayer Now CI passed. Could you check the PR?

**Comment by ibayer** [comment]
@chezou LGTM
Is there a way to test if the release upload etc. works? Or do I need to merge on master first and make a new release? I'm okay with this if there is not easy option to test otherwise.

**Comment by chezou** [comment]
If you push some tagged branch on GitHub like `test`, I think you can see uploaded files.

**Comment by ibayer** [comment]
Thanks, I will test it tonight and if it works merge and create a new release. :-)

**Comment by chezou** [comment]
Ah, sorry. We can’t upload before merging. The test tag is available after merging.

**Pull request merged**
